### ISSUE TITLE
有些脚本加载时：An error occurred converting string from UTF-8 to WStr

### ISSUE THREAD

**Issue by ieiian** [najoast/eluna_scripts#1]
超级商人和幻化大师加强版都会提示 UTF-8 报错，请问这应该如何解决？
![截屏2024-01-24 14 39 27](https://github.com/najoast/eluna_scripts/assets/63219448/f1d4929c-7791-4473-a77e-26e6c33dc589)

**Comment by najoast** [comment]
把 `unused` 那个目录整个删除掉，这里面的脚本是我备份用的，并没有经过实际的测试，所以不保证可运行。
